### PR TITLE
Add Zookeper logs and DC/OS version file to the bundle

### PR DESCRIPTION
**Pull request by surdy**
Added a couple of useful files to the bundle.

### CODE REVIEW

**Comment by surdy** [comment]
@mesosphere-mergebot test-it

**Comment by mhrabovcin** [comment]
@surdy @darkonie I'd like to bring to your attention recent change that got merged to `dcos` - https://github.com/dcos/dcos/pull/1192 . We're no longer writing any log messages to `/var/lib/dcos/exhibitor/zookeeper/zookeeper.out` file as it wasn't logrotated and it was growing unbounded. We still write all the log messages to `journald` so if you want to include ZK logs you have to get them from ZK.

**Comment by surdy** [comment]
@mhrabovcin Thanks for the heads up. So now the Zookeeper logs would show up in `dcos-exhibitor` logs ?

**Comment by mhrabovcin** [comment]
@surdy correct, Zookeeper logs are now available as part of `dcos-exhibitor`.

**Pull request closed without merging**
