### PR TITLE
3dt refactor

### PR DESCRIPTION
**Pull request by darkonie**
- add go vet command
 - refactor code to fix issues noticed by go vet
 - use dcos shared libs

### CODE REVIEW

**Comment by darkonie** [comment]
@mesosphere-mergebot test-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot test-it

**Comment by malnick** [comment]
:+1: :ship:

**Comment by orsenthil** [comment]
@malnick , @darkonie shall I ask mergebot to merge it? @darkonie  would you like to squash and force push it a single SHA?

**Comment by darkonie** [comment]
@orsenthil let's hold on for now, i need to make sure i don;t break anything
https://github.com/dcos/dcos/pull/1111
https://github.com/mesosphere/dcos-enterprise/pull/506

**Comment by darkonie** [comment]
i also had to make changes to gen i need to ship with bumped sha, unfortunately we cannot use bot to merge this change.

**Pull request merged**
